/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.warehouse.system.view;
import com.mycompany.warehouse.system.DatabaseConfig;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement; // Diperlukan untuk Simpan/Edit/Hapus
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ndesc
 */
public class BarangPanel extends javax.swing.JPanel {
  private int selectedId = -1; 

    /**
     * Creates new form BarangPanel
     */
    public BarangPanel() {
        initComponents();
            loadData(); // Tambahkan ini
    }
    public final void loadData() {
        DefaultTableModel model = new DefaultTableModel();
        // Tambahkan kolom ID di index 0
        model.addColumn("ID"); model.addColumn("Kode"); model.addColumn("Nama"); 
        model.addColumn("Kategori"); model.addColumn("Satuan");
        // (Kolom Berat dst opsional ditampilkan di UI, tapi wajib ada di model)

        try (Connection conn = DatabaseConfig.getConnection()) {
            String sql = "SELECT id, kode_item, nama_item, kategori, satuan, berat, panjang, lebar, tinggi, minimum_stok FROM items WHERE status_aktif = 1";
            ResultSet rs = conn.createStatement().executeQuery(sql);
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"), rs.getString("kode_item"), rs.getString("nama_item"),
                    rs.getString("kategori"), rs.getString("satuan"),
                    rs.getInt("berat"), rs.getInt("panjang"), rs.getInt("lebar"), 
                    rs.getInt("tinggi"), rs.getInt("minimum_stok")
                });
            }
            tableBarang.setModel(model);
            // Sembunyikan kolom ID (Index 0)
            tableBarang.getColumnModel().getColumn(0).setMinWidth(0);
            tableBarang.getColumnModel().getColumn(0).setMaxWidth(0);
        } catch (SQLException e) { JOptionPane.showMessageDialog(null, e.getMessage()); 
    }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        inputNama = new javax.swing.JTextField();
        inputBerat = new javax.swing.JSpinner();
        inputPanjang = new javax.swing.JSpinner();
        inputLebar = new javax.swing.JSpinner();
        inputTinggi = new javax.swing.JSpinner();
        inputMinimumStok = new javax.swing.JSpinner();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBarang = new javax.swing.JTable();
        inputKategori = new javax.swing.JComboBox<>();
        inputSatuan = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Barang");

        jLabel2.setText("Nama Barang");

        jLabel3.setText("Kategori");

        jLabel4.setText("Satuan");

        jLabel5.setText("Berat");

        jLabel6.setText("Panjang");

        jLabel7.setText("Lebar");

        jLabel8.setText("Tinggi");

        jLabel9.setText("Minimum Stok");

        inputNama.addActionListener(this::inputNamaActionPerformed);

        inputBerat.setModel(new javax.swing.SpinnerNumberModel(0, null, 99999, 1));

        inputPanjang.setModel(new javax.swing.SpinnerNumberModel(0, null, 99999, 1));

        inputLebar.setModel(new javax.swing.SpinnerNumberModel(0, null, 99999, 1));

        inputTinggi.setModel(new javax.swing.SpinnerNumberModel(0, null, 99999, 1));

        inputMinimumStok.setModel(new javax.swing.SpinnerNumberModel(0, null, 99999, 1));

        btnSimpan.setBackground(new java.awt.Color(39, 174, 96));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        btnEdit.setBackground(new java.awt.Color(243, 156, 18));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnDelete.setBackground(new java.awt.Color(231, 76, 60));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        tableBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBarangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableBarang);

        inputKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hardware", "Elektrikal", "Plumbing", "APD", "Kimia" }));

        btnReset.setBackground(new java.awt.Color(149, 165, 166));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete)
                                .addGap(18, 18, 18)
                                .addComponent(btnReset))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputMinimumStok, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(308, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(78, 78, 78)
                                    .addComponent(inputTinggi, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addGap(69, 69, 69)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(inputBerat, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                        .addComponent(inputPanjang)
                                        .addComponent(inputLebar))))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(inputNama, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                    .addComponent(inputKategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inputSatuan))))
                        .addContainerGap(308, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inputKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(inputBerat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(inputPanjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(inputLebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(inputTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(inputMinimumStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete)
                    .addComponent(btnReset))
                .addGap(58, 58, 58)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNamaActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // --- 1. VALIDASI INPUT TIDAK BOLEH KOSONG ---
            if (inputNama.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nama barang tidak boleh kosong!");
                inputNama.requestFocus(); // Arahkan kursor ke input yang kosong
                return;
            }

            if (inputSatuan.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Satuan barang tidak boleh kosong! (Contoh: Pcs, Box)");
                inputSatuan.requestFocus();
                return;
            }

            // Validasi tambahan: Cek jika JSpinner masih bernilai 0 (Opsional)
            if ((int) inputMinimumStok.getValue() <= 0) {
                int opsi = JOptionPane.showConfirmDialog(this, 
                    "Minimum stok bernilai 0 atau kurang. Tetap simpan?", 
                    "Peringatan", JOptionPane.YES_NO_OPTION);
                if (opsi == JOptionPane.NO_OPTION) return;
            }

            // --- 2. PROSES DATABASE ---
            String sql = "INSERT INTO items (kode_item, nama_item, kategori, satuan, berat, panjang, lebar, tinggi, minimum_stok, status_aktif) "
                       + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

            try (Connection conn = DatabaseConfig.getConnection()) {
                // --- A. GENERATE KODE ITEM OTOMATIS (ITM-001) ---
                String queryCek = "SELECT MAX(id) AS last_id FROM items"; // Menggunakan ID terakhir lebih akurat
                PreparedStatement psCek = conn.prepareStatement(queryCek);
                ResultSet rs = psCek.executeQuery();
                int urutan = 1;
                if (rs.next()) {
                    urutan = rs.getInt("last_id") + 1;
                }
                String kodeOtomatis = String.format("ITM-%03d", urutan); 

                // --- B. EKSEKUSI INSERT ---
                try (PreparedStatement ps = conn.prepareStatement(sql)) {
                    ps.setString(1, kodeOtomatis);
                    ps.setString(2, inputNama.getText().trim());
                    ps.setString(3, inputKategori.getSelectedItem().toString());
                    ps.setString(4, inputSatuan.getText().trim());

                    // Konversi Spinner ke Double/Integer secara aman
                    ps.setDouble(5, Double.parseDouble(inputBerat.getValue().toString()));
                    ps.setDouble(6, Double.parseDouble(inputPanjang.getValue().toString()));
                    ps.setDouble(7, Double.parseDouble(inputLebar.getValue().toString()));
                    ps.setDouble(8, Double.parseDouble(inputTinggi.getValue().toString()));

                    ps.setInt(9, (int) inputMinimumStok.getValue());
                    ps.setInt(10, 1); // status_aktif default 1

                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan dengan Kode: " + kodeOtomatis);

                    clearForm(); // Mengosongkan form setelah sukses
                    loadData();  // Refresh JTable
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Gagal simpan ke Database: " + e.getMessage());
            }
    }//GEN-LAST:event_btnSimpanActionPerformed


    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
      // 1. Validasi: Pastikan ada data yang dipilih (ID tidak -1)
        if (selectedId == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data di tabel yang ingin diubah!");
            return;
        }

        // 2. Validasi input kosong
        if (inputNama.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong!");
            return;
        }

        String sql = "UPDATE items SET nama_item=?, kategori=?, satuan=?, berat=?, panjang=?, lebar=?, tinggi=?, minimum_stok=? WHERE id=?";

        try (Connection conn = DatabaseConfig.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            // 3. Masukkan data dari form ke query
            ps.setString(1, inputNama.getText().trim());
            ps.setString(2, inputKategori.getSelectedItem().toString());
            ps.setString(3, inputSatuan.getText().trim());

            // Mengambil nilai Spinner
            ps.setInt(4, (int) inputBerat.getValue());
            ps.setInt(5, (int) inputPanjang.getValue());
            ps.setInt(6, (int) inputLebar.getValue());
            ps.setInt(7, (int) inputTinggi.getValue());
            ps.setInt(8, (int) inputMinimumStok.getValue());

            // Parameter WHERE id
            ps.setInt(9, selectedId);

            // 4. Eksekusi Update
            int rowsUpdated = ps.executeUpdate();
            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");

                // 5. Kembalikan kondisi form
                clearForm();    // Fungsi untuk mengosongkan input
         
              
                // 3. ATUR STATUS TOMBOL
                btnSimpan.setEnabled(true); // Mematikan tombol Simpan
                btnEdit.setEnabled(false);    // Pastikan tombol Edit menyala
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error Update: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
         int row = tableBarang.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data di tabel dulu!");
        return;
    }

    // Ambil ID dari kolom index 0, dan Nama dari kolom index 2 (sesuaikan indexnya)
    String id = tableBarang.getValueAt(row, 0).toString();
    String nama = tableBarang.getValueAt(row, 2).toString(); 

    int konfirmasi = JOptionPane.showConfirmDialog(this, 
            "Hapus data " + nama + " (ID: " + id + ")?", 
            "Konfirmasi", JOptionPane.YES_NO_OPTION);

    if (konfirmasi == JOptionPane.YES_OPTION) {
        // Gunakan nama tabel 'items' sesuai query INSERT Anda sebelumnya
        String sql = "DELETE FROM items WHERE id=?"; 
        
        try (Connection conn = DatabaseConfig.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            
            ps.setString(1, id);
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
         
            clearForm(); // Bersihkan form input
             btnSimpan.setEnabled(true); // Mematikan tombol Simpan
                btnEdit.setEnabled(false);    // Pastikan tombol Edit menyala
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error Hapus: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tableBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBarangMouseClicked
        int row = tableBarang.getSelectedRow();
        
    if (row != -1) {
        // 1. Ambil ID dari kolom pertama (index 0)
        String idStr = tableBarang.getValueAt(row, 0).toString();
        selectedId = Integer.parseInt(idStr); 

        // 2. Query ke database untuk mendapatkan data lengkap berdasarkan ID
        String sql = "SELECT * FROM items WHERE id = ?";
        
        try (Connection conn = DatabaseConfig.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            
            ps.setString(1, idStr);
            ResultSet rs = ps.executeQuery();
            
            if (rs.next()) {
                // 3. Set data ke Form Input dari hasil query (ResultSet)
                inputNama.setText(rs.getString("nama_item"));
                inputKategori.setSelectedItem(rs.getString("kategori"));
                inputSatuan.setText(rs.getString("satuan"));
                
                // Mengisi Spinner secara aman
                inputBerat.setValue(rs.getInt("berat"));
                inputPanjang.setValue(rs.getInt("panjang"));
                inputLebar.setValue(rs.getInt("lebar"));
                inputTinggi.setValue(rs.getInt("tinggi"));
                inputMinimumStok.setValue(rs.getInt("minimum_stok"));
                
               // 3. ATUR STATUS TOMBOL
                btnSimpan.setEnabled(false); // Mematikan tombol Simpan
                btnEdit.setEnabled(true);    // Pastikan tombol Edit menyala
               
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error ambil data: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_tableBarangMouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        clearForm(); 
    }//GEN-LAST:event_btnResetActionPerformed

private void clearForm() {
    inputNama.setText("");
    inputSatuan.setText("");
    inputKategori.setSelectedIndex(0);
    inputBerat.setValue(0);
    inputPanjang.setValue(0);
    inputLebar.setValue(0);
    inputTinggi.setValue(0);
    inputMinimumStok.setValue(0);
    inputNama.requestFocus();
    btnSimpan.setEnabled(true); // Mematikan tombol Simpan
    selectedId = -1; // Reset ID pilihan
       loadData(); // Refresh tabel
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JSpinner inputBerat;
    private javax.swing.JComboBox<String> inputKategori;
    private javax.swing.JSpinner inputLebar;
    private javax.swing.JSpinner inputMinimumStok;
    private javax.swing.JTextField inputNama;
    private javax.swing.JSpinner inputPanjang;
    private javax.swing.JTextField inputSatuan;
    private javax.swing.JSpinner inputTinggi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableBarang;
    // End of variables declaration//GEN-END:variables
}
