/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.warehouse.system.view;
//import com.mycompany.warehouse.system.DatabaseConfig;
import com.mycompany.warehouse.system.DatabaseConfig;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.HashMap;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
/**
 *
 * @author ndesc
 */
public class BarangMasukPanel extends javax.swing.JPanel {
   


    private final HashMap<String, Integer> supplierMap = new HashMap<>();
    private final HashMap<String, Integer> itemMap = new HashMap<>();
    private final HashMap<String, Integer> locationMap = new HashMap<>();
    /**
     * Creates new form BarangMasukPanel
     */
    public BarangMasukPanel() {
          initComponents();
            inputTanggalTerima.setDateFormatString("yyyy-MM-dd");
            inputTanggalTerima.getDateEditor().setEnabled(false);
            inputTanggalTerima.setDate(new java.util.Date());
            generateNomorPenerimaan();
            loadSupplier();
            loadItem();
            loadLocation();
            formatHarga();
    
        
    }
    private void formatHarga(){
      inputHarga.addKeyListener(new KeyAdapter() {

    @Override
    public void keyTyped(KeyEvent evt) {
            char c = evt.getKeyChar();
            String text = inputHarga.getText();
            // hanya angka dan titik
            if (!Character.isDigit(c)
                    && c != '.'
                    && c != KeyEvent.VK_BACK_SPACE) {
                evt.consume();
            }
            // cegah titik lebih dari satu
            if (c == '.' && text.contains(".")) {

                evt.consume();
            }
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelNomorPenerimaan = new javax.swing.JLabel();
        inputSupplier = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        inputKodeBarang = new javax.swing.JComboBox<>();
        labelNamaBarang = new javax.swing.JLabel();
        inputQty = new javax.swing.JSpinner();
        labelSatuan = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        inputLokasi = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        inputTanggalTerima = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        inputHarga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        inputKondisiBarang = new javax.swing.JComboBox<>();

        jScrollPane1.setViewportView(jEditorPane1);

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Input Barang Masuk");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 27, 0, 0);
        add(jLabel1, gridBagConstraints);

        jLabel2.setText("Nomor Penerimaan      :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 27, 0, 0);
        add(jLabel2, gridBagConstraints);

        jLabel4.setText("Tanggal Terima             :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 27, 0, 0);
        add(jLabel4, gridBagConstraints);

        jLabel5.setText("Supplier                        :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 27, 0, 0);
        add(jLabel5, gridBagConstraints);

        labelNomorPenerimaan.setText("GR-2026-001");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 0);
        add(labelNomorPenerimaan, gridBagConstraints);

        inputSupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PT A", "PT B", "PT C" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 71;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 40);
        add(inputSupplier, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Barang");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(52, 27, 0, 0);
        add(jLabel8, gridBagConstraints);

        inputKodeBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ITM-001", "ITM-002", "ITM-003", "ITM-004" }));
        inputKodeBarang.addActionListener(this::inputKodeBarangActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 64;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 40);
        add(inputKodeBarang, gridBagConstraints);

        labelNamaBarang.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        add(labelNamaBarang, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 79;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 40);
        add(inputQty, gridBagConstraints);

        labelSatuan.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        add(labelSatuan, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jLabel11, gridBagConstraints);

        inputLokasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LOC-A-01-1", "LOC-A-01-2", "LOC-A-01-3" }));
        inputLokasi.setMinimumSize(new java.awt.Dimension(64, 22));
        inputLokasi.addActionListener(this::inputLokasiActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 39;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        add(inputLokasi, gridBagConstraints);

        jLabel12.setText("Kode Barang                 :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 176;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 27, 0, 0);
        add(jLabel12, gridBagConstraints);

        jLabel13.setText("Nama Barang                :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 176;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 27, 0, 0);
        add(jLabel13, gridBagConstraints);

        jLabel14.setText("Qty                               :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 178;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 27, 0, 0);
        add(jLabel14, gridBagConstraints);

        jLabel15.setText("Satuan                          :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 47;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 27, 0, 0);
        add(jLabel15, gridBagConstraints);

        jLabel16.setText("Lokasi                           :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 178;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 27, 0, 0);
        add(jLabel16, gridBagConstraints);

        btnSimpan.setBackground(new java.awt.Color(39, 174, 96));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 60, 40, 0);
        add(btnSimpan, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 61;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 40);
        add(inputTanggalTerima, gridBagConstraints);

        jLabel6.setText("Harga                           :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 178;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 27, 0, 0);
        add(jLabel6, gridBagConstraints);

        inputHarga.addActionListener(this::inputHargaActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 79;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 40);
        add(inputHarga, gridBagConstraints);

        jLabel7.setText("Kondisi Barang             :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 27, 0, 0);
        add(jLabel7, gridBagConstraints);

        inputKondisiBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baik", "Rusak", "Cacat" }));
        inputKondisiBarang.setMinimumSize(new java.awt.Dimension(64, 22));
        inputKondisiBarang.addActionListener(this::inputKondisiBarangActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 65;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        add(inputKondisiBarang, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void inputKodeBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKodeBarangActionPerformed
      
        try {
            // Cegah null saat pertama load
            if (inputKodeBarang.getSelectedItem() == null) {
                return;
            }
            String kodeBarang =
                    inputKodeBarang.getSelectedItem().toString();
            Connection conn =
                    DatabaseConfig.getConnection();
            String sql = """
                    SELECT nama_item, satuan
                    FROM items
                    WHERE kode_item = ?
                    """;

            PreparedStatement ps =
                    conn.prepareStatement(sql);
            ps.setString(1, kodeBarang);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                String namaBarang =
                        rs.getString("nama_item");
                String satuan =
                        rs.getString("satuan");
                // Update label otomatis
                labelNamaBarang.setText(namaBarang);
                labelSatuan.setText(satuan);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_inputKodeBarangActionPerformed

    private void inputLokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputLokasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputLokasiActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
            Connection conn = null;

          try {

              /*
               =====================================
               VALIDASI
               =====================================
               */
              int qty = Integer.parseInt(
                      inputQty.getValue().toString()
              );
              if (qty <= 0) {
                  JOptionPane.showMessageDialog(
                          this,
                          "Qty harus lebih dari 0"
                  );
                  return;
              }

              if (inputHarga.getText().trim().isEmpty()) {
                  JOptionPane.showMessageDialog(
                          this,
                          "Harga wajib diisi"
                  );
                  return;
              }

              /*
               =====================================
               AMBIL DATA FORM
               =====================================
               */
              double harga =
                      Double.parseDouble(inputHarga.getText());

              String kondisiBarang =
                      inputKondisiBarang
                              .getSelectedItem()
                              .toString();
              String supplierName =
                      inputSupplier.getSelectedItem().toString();
              String kodeBarang =
                      inputKodeBarang.getSelectedItem().toString();
              String lokasiName =
                      inputLokasi.getSelectedItem().toString();
              String catatan = null;
//                      inputCatatan.getText().trim();
              int supplierId =
                      supplierMap.get(supplierName);
              int itemId =
                      itemMap.get(kodeBarang);
              int locationId =
                      locationMap.get(lokasiName);
              String nomorPenerimaan =
                      labelNomorPenerimaan.getText();
              SimpleDateFormat sdf =
                      new SimpleDateFormat("yyyy-MM-dd");
              String tanggalTerima =
                      sdf.format(inputTanggalTerima.getDate());
              String satuan =
                      labelSatuan.getText();
              String status = "RECEIVED";

              /*
               =====================================
               DATABASE CONNECTION
               =====================================
               */
              conn = DatabaseConfig.getConnection();

              /*
               =====================================
               MATIKAN AUTO COMMIT
               =====================================
               */
              conn.setAutoCommit(false);

              /*
               =====================================
               GENERATE BATCH LOT
               =====================================
               */
              String noBatchLot =
                      generateBatchLot(conn);

              /*
               =====================================
               1. INSERT INBOUND TRANSACTION
               =====================================
               */
              String inboundSql = """
                      INSERT INTO inbound_transactions
                      (
                          nomor_penerimaan,
                          tanggal_terima,
                          supplier_id,
                          item_id,
                          qty,
                          satuan,
                          harga_satuan,
                          no_batch_lot,
                          kondisi_barang,
                          location_id,
                          catatan,
                          status
                      )
                      VALUES
                      (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                      """;

              PreparedStatement psInbound =
                      conn.prepareStatement(inboundSql);
              psInbound.setString(1, nomorPenerimaan);
              psInbound.setString(2, tanggalTerima);
              psInbound.setInt(3, supplierId);
              psInbound.setInt(4, itemId);
              psInbound.setInt(5, qty);
              psInbound.setString(6, satuan);
              psInbound.setDouble(7, harga);
              psInbound.setString(8, noBatchLot);
              psInbound.setString(9, kondisiBarang);
              psInbound.setInt(10, locationId);

              /*
               jika kosong -> NULL
               */
              if (catatan == null) {
                  psInbound.setNull(11, java.sql.Types.VARCHAR);
              } else {
                  psInbound.setString(11, catatan);
              }
              psInbound.setString(12, status);
              psInbound.executeUpdate();
              /*
               =====================================
               2. CEK INVENTORY
               =====================================
               */
              String checkInventorySql = """
                      SELECT id, stok_terkini
                      FROM inventory
                      WHERE item_id = ?
                      AND location_id = ?
                      """;

              PreparedStatement psCheck =
                      conn.prepareStatement(checkInventorySql);

              psCheck.setInt(1, itemId);

              psCheck.setInt(2, locationId);

              ResultSet rs =
                      psCheck.executeQuery();

              int stockSebelum = 0;

              int stockSesudah = 0;

              /*
               =====================================
               JIKA INVENTORY SUDAH ADA
               =====================================
               */
              if (rs.next()) {

                  stockSebelum =
                          rs.getInt("stok_terkini");

                  stockSesudah =
                          stockSebelum + qty;

                  String updateInventorySql = """
                          UPDATE inventory
                          SET stok_terkini = ?
                          WHERE item_id = ?
                          AND location_id = ?
                          """;

                  PreparedStatement psUpdateInventory =
                          conn.prepareStatement(updateInventorySql);

                  psUpdateInventory.setInt(1, stockSesudah);
                  psUpdateInventory.setInt(2, itemId);
                  psUpdateInventory.setInt(3, locationId);
                  psUpdateInventory.executeUpdate();

              } else {

                  /*
                   =====================================
                   JIKA INVENTORY BELUM ADA
                   =====================================
                   */
                  stockSebelum = 0;

                  stockSesudah = qty;

                  String insertInventorySql = """
                          INSERT INTO inventory
                          (
                              item_id,
                              location_id,
                              stok_terkini
                          )
                          VALUES
                          (?, ?, ?)
                          """;

                  PreparedStatement psInsertInventory =
                          conn.prepareStatement(insertInventorySql);

                  psInsertInventory.setInt(1, itemId);

                  psInsertInventory.setInt(2, locationId);

                  psInsertInventory.setInt(3, stockSesudah);

                  psInsertInventory.executeUpdate();
              }

              /*
               =====================================
               3. INSERT STOCK HISTORY
               =====================================
               */
              String stockHistorySql = """
                      INSERT INTO stock_history
                      (
                          jenis_transaksi,
                          nomor_referensi,
                          item_id,
                          location_id,
                          qty,
                          stock_sebelum,
                          stock_sesudah
                      )
                      VALUES
                      (?, ?, ?, ?, ?, ?, ?)
                      """;

              PreparedStatement psHistory =
                      conn.prepareStatement(stockHistorySql);

              psHistory.setString(1, "inbound");
              psHistory.setString(2, nomorPenerimaan);
              psHistory.setInt(3, itemId);
              psHistory.setInt(4, locationId);
              psHistory.setInt(5, qty);
              psHistory.setInt(6, stockSebelum);
              psHistory.setInt(7, stockSesudah);
              psHistory.executeUpdate();

              /*
               =====================================
               COMMIT TRANSACTION
               =====================================
               */
              conn.commit();

              JOptionPane.showMessageDialog(
                      this,
                      "Barang masuk berhasil disimpan\n"
                      + "Batch : " + noBatchLot
              );
              clearForm();
              generateNomorPenerimaan();

          } catch (Exception e) {

              e.printStackTrace();

              /*
               =====================================
               ROLLBACK
               =====================================
               */
              try {
                  if (conn != null) {
                      conn.rollback();
                  }
              } catch (SQLException ex) {
                  ex.printStackTrace();
              }
              JOptionPane.showMessageDialog(
                      this,
                      "Transaction gagal"
              );
          } finally {
              /*
               =====================================
               AKTIFKAN AUTO COMMIT
               =====================================
               */
              try {
                  if (conn != null) {
                      conn.setAutoCommit(true);
                      conn.close();
                  }
              } catch (SQLException e) {
                  e.printStackTrace();
              }
          }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void inputKondisiBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKondisiBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputKondisiBarangActionPerformed

    private void inputHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputHargaActionPerformed

public void generateNomorPenerimaan() {

    try {
           Connection conn = DatabaseConfig.getConnection();
        String sql = """
                SELECT COUNT(*) + 1 as total
                FROM inbound_transactions
                """;

        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();
        if (rs.next()) {
            int nomor = rs.getInt("total");
            String nomorFormat = String.format("GR-2026-%03d", nomor);
            labelNomorPenerimaan.setText(nomorFormat);
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}

public void loadSupplier() {

    try {

        Connection conn = DatabaseConfig.getConnection();
        String sql = "SELECT id, nama_supplier FROM suppliers";
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();
        inputSupplier.removeAllItems();
        while (rs.next()) {
            int id = rs.getInt("id");
            String nama = rs.getString("nama_supplier");
            supplierMap.put(nama, id);
            inputSupplier.addItem(nama);
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}

public void loadItem() {

    try {

        Connection conn = DatabaseConfig.getConnection();

        String sql = """
                SELECT id, kode_item
                FROM items
                """;
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();
        inputKodeBarang.removeAllItems();

        while (rs.next()) {
            int id = rs.getInt("id");
            String kodeBarang = rs.getString("kode_item");
            itemMap.put(kodeBarang, id);
            inputKodeBarang.addItem(kodeBarang);
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}
public void loadLocation() {

    try {

        Connection conn = DatabaseConfig.getConnection();

        String sql = """
                SELECT id, kode_lokasi
                FROM locations
                """;

        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();
        inputLokasi.removeAllItems();

        while (rs.next()) {
            int id = rs.getInt("id");
            String lokasi = rs.getString("kode_lokasi");
            locationMap.put(lokasi, id);
            inputLokasi.addItem(lokasi);
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}
private void clearForm() {

    // Reset supplier ke item pertama
    inputSupplier.setSelectedIndex(0);
    // Reset kode barang ke item pertama
    inputKodeBarang.setSelectedIndex(0);
    // Reset lokasi ke item pertama
    inputLokasi.setSelectedIndex(0);
    // Reset qty
    inputQty.setValue(0);
     // Reset Harga
    inputHarga.setText("");
    // Reset tanggal ke hari ini
    inputTanggalTerima.setDate(new java.util.Date());
    // Reset label nama barang & satuan
    labelNamaBarang.setText("-");
    labelSatuan.setText("-");
    // Generate ulang nomor penerimaan
    generateNomorPenerimaan();
}

private String generateBatchLot(Connection conn)
        throws SQLException {

    /*
     =====================================
     AMBIL 2 DIGIT TAHUN SEKARANG
     =====================================
     */
    String tahun =
            new SimpleDateFormat("yy")
                    .format(new java.util.Date());

    /*
     =====================================
     HITUNG JUMLAH BATCH TAHUN INI
     =====================================
     */
    String sql = """
            SELECT COUNT(*) + 1 as total
            FROM inbound_transactions
            WHERE no_batch_lot LIKE ?
            """;

    PreparedStatement ps =
            conn.prepareStatement(sql);

    ps.setString(1, "BATCH-" + tahun + "%");

    ResultSet rs = ps.executeQuery();

    if (rs.next()) {

        int nomor = rs.getInt("total");

        /*
         FORMAT:
         01
         02
         03
         */
        String urutan =
                String.format("%02d", nomor);

        return "BATCH-" + tahun + urutan;
    }

    return "BATCH-" + tahun + "01";
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JTextField inputHarga;
    private javax.swing.JComboBox<String> inputKodeBarang;
    private javax.swing.JComboBox<String> inputKondisiBarang;
    private javax.swing.JComboBox<String> inputLokasi;
    private javax.swing.JSpinner inputQty;
    private javax.swing.JComboBox<String> inputSupplier;
    private com.toedter.calendar.JDateChooser inputTanggalTerima;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNamaBarang;
    private javax.swing.JLabel labelNomorPenerimaan;
    private javax.swing.JLabel labelSatuan;
    // End of variables declaration//GEN-END:variables
}
