/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.warehouse.system.view;
import com.mycompany.warehouse.system.service.DashboardService;
import com.mycompany.warehouse.system.HistoryFrame;
import com.mycompany.warehouse.system.model.User;
import com.mycompany.warehouse.system.service.Session;
import javax.swing.JOptionPane;
import java.awt.CardLayout;
import java.awt.Color; 
import javax.swing.*;
/**
 *
 * @author ndesc
 */
public class ContentFrame extends javax.swing.JFrame {
    
//    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardFrame.class.getName());
 
    // Tambahkan variabel global untuk menyimpan user yang sedang login
    /**
     * Creates new form DashboardFrame
     * 
     */
   // 1. DEKLARASI VARIABEL GLOBAL (Letakkan di bawah nama class)
    private final DashboardStaff menuDashboardStaff;
    private final BarangPanel menuBarang;
    private final BarangMasukPanel menuBarangMasuk;
    private final BarangKeluarPanel menuBarangKeluar;
    private final SupplierPanel menuSupplier;

    // 2. CONSTRUCTOR UTAMA
    public ContentFrame() {
                initComponents();

                // 3. INISIALISASI OBJEK PANEL (Dimasukkan ke dalam constructor)
                menuBarang = new BarangPanel();
                menuDashboardStaff = new DashboardStaff();
                menuBarangMasuk = new BarangMasukPanel();
                menuBarangKeluar = new BarangKeluarPanel();
                menuSupplier = new SupplierPanel();

                // 4. MASUKKAN PANEL KE CARDLAYOUT
                panelContent.add(menuBarang, "cardBarang");
                panelContent.add(menuDashboardStaff, "dashboardStaff");
                panelContent.add(menuSupplier, "cardSupplier");
                panelContent.add(menuBarangMasuk, "cardBarangMasuk");
                panelContent.add(menuBarangKeluar, "cardBarangKeluar");
                

                // 5. ATUR TAMPILAN AWAL
                aturHakAkses();
          
                setMenuColor(btnMDashboard);

                this.setExtendedState(ContentFrame.MAXIMIZED_BOTH);

        // ... Sisa kode fungsi tombol Anda di bawah ini ...
    }
     private void aturHakAkses() {
         User user = Session.getUser(); 
        if (user != null) { 
            String role = user.getRole(); 

            if (role.equalsIgnoreCase("staff")) { 
                LMaster.setVisible(false); 
                btnMUser.setVisible(false); 
                btnMBarang.setVisible(false); 
                btnMLokasi.setVisible(false); 
                btnMSupplier.setVisible(false); 

                loadDashboardStaff(); // Memuat panel staff
            } else if (role.equalsIgnoreCase("spv")) {
                // Tambahkan logika batasan menu untuk SPV di sini jika ada
                // Contoh: loadDashboardSPV();
            } else { 
                LTransaction.setVisible(false); 
                btnMBarangMasuk.setVisible(false); 
                btnMBarangKeluar.setVisible(false); 
                btnMTransferBarang.setVisible(false);
               
                loadDashboardAdmin(); // Memuat panel admin
            } 
        } 
    }
     // FUNGSI UNTUK MEMUAT DASHBOARD STAFF
        private void loadDashboardStaff() {

             DashboardStaff dbStaff = new DashboardStaff();
            panelContent.add(dbStaff, "dashboardStaff");
            CardLayout cl = (CardLayout) panelContent.getLayout();
            cl.show(panelContent, "dashboardStaff");
        }

        // FUNGSI UNTUK MEMUAT DASHBOARD ADMIN
        private void loadDashboardAdmin() {   
//        lbluser.setText(String.valueOf(DashboardService.getTotalUsers()));
//        lblsupplier.setText(String.valueOf(DashboardService.getTotalSuppliers()));
//        lbllokasi.setText(String.valueOf(DashboardService.getTotalLocations()));
//        lblbarang.setText(String.valueOf(DashboardService.getTotalItems()));
             DashboardAdmin dbAdmin = new DashboardAdmin();
            panelContent.add(dbAdmin, "dashboardAdmin");
            CardLayout cl = (CardLayout) panelContent.getLayout();
            cl.show(panelContent, "dashboardAdmin");        
        }
     
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSidebar = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        btnMBarang = new javax.swing.JButton();
        btnMLokasi = new javax.swing.JButton();
        btnMDashboard = new javax.swing.JButton();
        btnMUser = new javax.swing.JButton();
        btnMSupplier = new javax.swing.JButton();
        btnMBarangMasuk = new javax.swing.JButton();
        btnMBarangKeluar = new javax.swing.JButton();
        btnMTransferBarang = new javax.swing.JButton();
        LTransaction = new javax.swing.JLabel();
        LMaster = new javax.swing.JLabel();
        panelContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelSidebar.setBackground(new java.awt.Color(153, 255, 255));
        panelSidebar.setForeground(new java.awt.Color(255, 255, 255));

        btnLogout.setBackground(new java.awt.Color(255, 51, 51));
        btnLogout.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        btnMBarang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMBarang.setText("Barang");
        btnMBarang.addActionListener(this::btnMBarangActionPerformed);

        btnMLokasi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMLokasi.setText("Lokasi");
        btnMLokasi.addActionListener(this::btnMLokasiActionPerformed);

        btnMDashboard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMDashboard.setText("Dashboard");
        btnMDashboard.addActionListener(this::btnMDashboardActionPerformed);

        btnMUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMUser.setText("User");
        btnMUser.setMaximumSize(new java.awt.Dimension(89, 23));
        btnMUser.setPreferredSize(new java.awt.Dimension(89, 23));

        btnMSupplier.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMSupplier.setText("Supplier");
        btnMSupplier.setMaximumSize(new java.awt.Dimension(89, 23));
        btnMSupplier.setPreferredSize(new java.awt.Dimension(89, 23));
        btnMSupplier.addActionListener(this::btnMSupplierActionPerformed);

        btnMBarangMasuk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMBarangMasuk.setText("Barang Masuk");
        btnMBarangMasuk.addActionListener(this::btnMBarangMasukActionPerformed);

        btnMBarangKeluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMBarangKeluar.setText("Barang Keluar");
        btnMBarangKeluar.addActionListener(this::btnMBarangKeluarActionPerformed);

        btnMTransferBarang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMTransferBarang.setText("Transfer Barang");
        btnMTransferBarang.addActionListener(this::btnMTransferBarangActionPerformed);

        LTransaction.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LTransaction.setForeground(new java.awt.Color(43, 146, 229));
        LTransaction.setText("Transaction");

        LMaster.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LMaster.setForeground(new java.awt.Color(43, 146, 229));
        LMaster.setText("Master");

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMLokasi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMBarangMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMBarangKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMTransferBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSidebarLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(LTransaction))
                    .addGroup(panelSidebarLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(LMaster))
                    .addGroup(panelSidebarLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnLogout)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LMaster)
                .addGap(5, 5, 5)
                .addComponent(btnMUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMBarang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LTransaction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMBarangMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMBarangKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMTransferBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnLogout)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        getContentPane().add(panelSidebar, java.awt.BorderLayout.LINE_START);

        panelContent.setBackground(new java.awt.Color(51, 51, 51));
        panelContent.setLayout(new java.awt.CardLayout());
        getContentPane().add(panelContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
      // 1. Konfirmasi ke user agar tidak tidak sengaja logout
        int opsi = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Apakah Anda yakin ingin logout?", "Konfirmasi Logout", 
                javax.swing.JOptionPane.YES_NO_OPTION);

        if (opsi == javax.swing.JOptionPane.YES_OPTION) {
            // 2. Bersihkan data user dari Session
            com.mycompany.warehouse.system.service.Session.clear();
            

            // 3. Tampilkan kembali form Login
            new com.mycompany.warehouse.system.view.FormLogin().setVisible(true);

            // 4. Tutup dashboard saat ini
            this.dispose();
        } // Menutup aplikasi

    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnMLokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMLokasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMLokasiActionPerformed

    private void btnMDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMDashboardActionPerformed
         User user = Session.getUser();

        CardLayout cl = (CardLayout) panelContent.getLayout();

        if (user.getRole().equalsIgnoreCase("staff")) {
            if (DashboardStaff.instance != null) {
                DashboardStaff.instance.loadData();
                DashboardStaff.instance.loadDataCount();
            }
            cl.show(panelContent, "dashboardStaff");

        } else {
              DashboardStaff.instance.loadData();
                DashboardStaff.instance.loadDataCount();
            cl.show(panelContent, "dashboardAdmin");
        }

             setMenuColor(btnMDashboard); 
    }//GEN-LAST:event_btnMDashboardActionPerformed

    private void btnMBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMBarangActionPerformed
    CardLayout cl = (CardLayout) panelContent.getLayout();
        cl.show(panelContent, "cardBarang");
         setMenuColor(btnMBarang); 
    }//GEN-LAST:event_btnMBarangActionPerformed

    private void btnMBarangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMBarangMasukActionPerformed
          CardLayout cl = (CardLayout) panelContent.getLayout();
          cl.show(panelContent, "cardBarangMasuk");
         setMenuColor(btnMBarangMasuk); 
         menuBarangMasuk.generateNomorPenerimaan();
            menuBarangMasuk.loadSupplier();
            menuBarangMasuk.loadItem();
            menuBarangMasuk.loadLocation();
    }//GEN-LAST:event_btnMBarangMasukActionPerformed

    private void btnMBarangKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMBarangKeluarActionPerformed
        // TODO add your handling code here:
             CardLayout cl = (CardLayout) panelContent.getLayout();
          cl.show(panelContent, "cardBarangKeluar");
         setMenuColor(btnMBarangKeluar); 
         menuBarangKeluar.loadBarangFromInventory();
    }//GEN-LAST:event_btnMBarangKeluarActionPerformed

    private void btnMTransferBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMTransferBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMTransferBarangActionPerformed

    private void btnMSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMSupplierActionPerformed
        CardLayout cl = (CardLayout) panelContent.getLayout();
        cl.show(panelContent, "cardSupplier");
         setMenuColor(btnMSupplier); 
    }//GEN-LAST:event_btnMSupplierActionPerformed
private void setMenuColor(JButton activeBtn) {
     // Contoh menggunakan Opsi 1 (Kontras Profesional)
    Color warnaSidebar = new Color(153, 255, 255);
    Color warnaAktif = new Color(0, 153, 153); // Hijau-Biru gelap
    Color teksPutih = Color.WHITE;
    Color teksHitam = Color.BLACK;

    // Reset semua tombol ke warna standar sidebar
    btnMDashboard.setBackground(warnaSidebar);
    btnMDashboard.setForeground(teksHitam);
    
    btnMBarang.setBackground(warnaSidebar);
    btnMBarang.setForeground(teksHitam);
    
    btnMSupplier.setBackground(warnaSidebar);
    btnMSupplier.setForeground(teksHitam);
    
    btnMUser.setBackground(warnaSidebar);
    btnMUser.setForeground(teksHitam);
    
    btnMLokasi.setBackground(warnaSidebar);
    btnMLokasi.setForeground(teksHitam);
   
    
    btnMBarangMasuk.setBackground(warnaSidebar);
    btnMBarangMasuk.setForeground(teksHitam);
    
    btnMBarangKeluar.setBackground(warnaSidebar);
    btnMBarangKeluar.setForeground(teksHitam);
    

    // Set tombol aktif
    activeBtn.setBackground(warnaAktif);
    activeBtn.setForeground(teksPutih); // Ubah teks jadi putih agar kontras
}
    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LMaster;
    private javax.swing.JLabel LTransaction;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMBarang;
    private javax.swing.JButton btnMBarangKeluar;
    private javax.swing.JButton btnMBarangMasuk;
    private javax.swing.JButton btnMDashboard;
    private javax.swing.JButton btnMLokasi;
    private javax.swing.JButton btnMSupplier;
    private javax.swing.JButton btnMTransferBarang;
    private javax.swing.JButton btnMUser;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelSidebar;
    // End of variables declaration//GEN-END:variables
}
