/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.warehouse.system.view;

import com.mycompany.warehouse.system.DatabaseConfig;
import com.mycompany.warehouse.system.service.DashboardService;
import static com.mycompany.warehouse.system.view.DashboardManager.instance;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import java.io.InputStream;

/**
 *
 * @author ndesc
 */
public class DashboardManager extends javax.swing.JPanel {
public static DashboardManager instance;
    /**
     * Creates new form DashboardManager
     */
    public DashboardManager() {
          initComponents();
         instance = this;
         loadDataInventory();
         loadDataAktifitas();
         loadDataCount();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        LBarangMasuk = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        LInventory = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        LBarangKeluar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TInventory = new javax.swing.JTable();
        txtSearchInventory = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BReportInventory = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TActivity = new javax.swing.JTable();
        BReportActivity = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSearchActivity = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(170, 166, 166));
        jLabel1.setText("Dashboard Manager");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(170, 166, 166));
        jLabel10.setText("Inventory");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(15, 23, 42));
        jLabel5.setText("Barang Masuk");

        LBarangMasuk.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LBarangMasuk.setForeground(new java.awt.Color(15, 23, 42));
        LBarangMasuk.setText("2000");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(LBarangMasuk)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBarangMasuk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(15, 23, 42));
        jLabel4.setText("Inventory");

        LInventory.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LInventory.setForeground(new java.awt.Color(15, 23, 42));
        LInventory.setText("2000");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(LInventory)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LInventory)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(15, 23, 42));
        jLabel6.setText("Barang Keluar");

        LBarangKeluar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LBarangKeluar.setForeground(new java.awt.Color(15, 23, 42));
        LBarangKeluar.setText("2000");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(LBarangKeluar)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBarangKeluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama Barang", "Lokasi", "Stok Terkini"
            }
        ));
        jScrollPane1.setViewportView(TInventory);

        txtSearchInventory.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtSearchInventory.addActionListener(this::txtSearchInventoryActionPerformed);
        txtSearchInventory.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchInventoryKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Cari inventory");

        BReportInventory.setBackground(new java.awt.Color(255, 51, 102));
        BReportInventory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BReportInventory.setForeground(new java.awt.Color(255, 255, 255));
        BReportInventory.setText("Report");
        BReportInventory.addActionListener(this::BReportInventoryActionPerformed);

        TActivity.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Jam", "Aktifitas", "Stok Sebelum", "Stok Sesudah"
            }
        ));
        jScrollPane2.setViewportView(TActivity);

        BReportActivity.setBackground(new java.awt.Color(255, 51, 102));
        BReportActivity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BReportActivity.setForeground(new java.awt.Color(255, 255, 255));
        BReportActivity.setText("Report");
        BReportActivity.addActionListener(this::BReportActivityActionPerformed);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(170, 166, 166));
        jLabel11.setText("Activity");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Cari Aktifitas");

        txtSearchActivity.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtSearchActivity.addActionListener(this::txtSearchActivityActionPerformed);
        txtSearchActivity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchActivityKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtSearchInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(12, 12, 12)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(BReportInventory)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel11)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtSearchActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BReportActivity)
                            .addGap(51, 51, 51))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63)
                .addComponent(jLabel10)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchInventory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(BReportInventory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel11)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BReportActivity)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearchActivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchInventoryActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_txtSearchInventoryActionPerformed

    private void txtSearchInventoryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchInventoryKeyReleased
           cariInventory();

    }//GEN-LAST:event_txtSearchInventoryKeyReleased

    private void BReportInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BReportInventoryActionPerformed
          try {

                InputStream reportStream =
                    getClass().getResourceAsStream(
                        "/report/ReportInventory.jasper"
                    );

                HashMap<String, Object> parameters =
                    new HashMap<>();

                JasperPrint print =
                    JasperFillManager.fillReport(
                        reportStream,
                        parameters,
                        DatabaseConfig.getConnection()
                    );

                JasperViewer.viewReport(print, false);

            } catch (Exception e) {

                e.printStackTrace();
            }
    }//GEN-LAST:event_BReportInventoryActionPerformed

    private void BReportActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BReportActivityActionPerformed
          try {

                InputStream reportStream =
                    getClass().getResourceAsStream(
                        "/report/ReportHistory.jasper"
                    );

                HashMap<String, Object> parameters =
                    new HashMap<>();

                JasperPrint print =
                    JasperFillManager.fillReport(
                        reportStream,
                        parameters,
                        DatabaseConfig.getConnection()
                    );

                JasperViewer.viewReport(print, false);

            } catch (Exception e) {

                e.printStackTrace();
            }
    }//GEN-LAST:event_BReportActivityActionPerformed

    private void txtSearchActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActivityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActivityActionPerformed

    private void txtSearchActivityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchActivityKeyReleased
        // TODO add your handling code here:
        cariActivity();
    }//GEN-LAST:event_txtSearchActivityKeyReleased
   public final void loadDataCount(){
       LInventory.setText(String.valueOf(DashboardService.getTotalItemsInventory()));
        LBarangMasuk.setText(String.valueOf(DashboardService.getTotalItemsMasuk()));
        LBarangKeluar.setText(String.valueOf(DashboardService.getTotalItemsKeluar()));
    }
   
    public final void loadDataAktifitas() { 
             DefaultTableModel model = new DefaultTableModel() {
                 // Best practice: Membuat sel tabel tidak bisa diedit secara manual oleh user
                 @Override
                 public boolean isCellEditable(int row, int column) {
                     return false;
                 }
             };

     // Tambahkan kolom ID di index 0 
     model.addColumn("ID"); 
     model.addColumn("Jam"); 
     model.addColumn("Aktifitas"); 
     model.addColumn("Barang"); 
      model.addColumn("Lokasi"); 
     model.addColumn("Stok Sebelum"); 
     model.addColumn("Stok Sesudah"); 

     String sql = """
         SELECT sh.id, sh.waktu_transaksi, sh.jenis_transaksi, i.nama_item,l.kode_lokasi, sh.stock_sebelum, sh.stock_sesudah 
         FROM stock_history sh 
         INNER JOIN items i ON sh.item_id = i.id
         INNER JOIN locations l ON sh.location_id = l.id
         ORDER BY sh.id DESC
         """;

         // Menggunakan try-with-resources untuk menutup conn, stmt, dan rs secara otomatis dan aman
         try (Connection conn = DatabaseConfig.getConnection();
              PreparedStatement ps = conn.prepareStatement(sql);
              ResultSet rs = ps.executeQuery()) { 

             while (rs.next()) { 
                 model.addRow(new Object[]{ 
                     rs.getInt("id"), 
                     rs.getString("waktu_transaksi"),
                     rs.getString("jenis_transaksi"), 
                     rs.getString("nama_item"), 
                     rs.getString("kode_lokasi"), 
                     rs.getString("stock_sebelum"), 
                     rs.getString("stock_sesudah") 
                 }); 
             } 

             // Atur model ke tabel UI
             TActivity.setModel(model); 

             // Beritahu UI bahwa data telah berubah agar visual langsung ter-render ulang
             model.fireTableDataChanged();

             // Sembunyikan kolom ID (Index 0) secara total agar aman dari resize manual user
             TActivity.getColumnModel().getColumn(0).setMinWidth(0); 
             TActivity.getColumnModel().getColumn(0).setMaxWidth(0); 
             TActivity.getColumnModel().getColumn(0).setPreferredWidth(0);

         } catch (SQLException e) { 
             JOptionPane.showMessageDialog(null, "Gagal memuat data: " + e.getMessage()); 
         } 
     }
   
    public final void loadDataInventory() { 
                DefaultTableModel model = new DefaultTableModel() {
                    // Best practice: Membuat sel tabel tidak bisa diedit secara manual oleh user
                    @Override
                    public boolean isCellEditable(int row, int column) {
                        return false;
                    }
                };

        // Tambahkan kolom ID di index 0 
        model.addColumn("ID"); 
        model.addColumn("Nama Barang"); 
        model.addColumn("Lokasi"); 
        model.addColumn("Stok Terkini"); 
  

        String sql = """
            SELECT sh.id,  i.nama_item,l.kode_lokasi, sh.stok_terkini
                        FROM inventory sh 
                        INNER JOIN items i ON sh.item_id = i.id
                        INNER JOIN locations l ON sh.location_id = l.id
                        ORDER BY sh.id DESC
            """;

            // Menggunakan try-with-resources untuk menutup conn, stmt, dan rs secara otomatis dan aman
            try (Connection conn = DatabaseConfig.getConnection();
                 PreparedStatement ps = conn.prepareStatement(sql);
                 ResultSet rs = ps.executeQuery()) { 

                while (rs.next()) { 
                    model.addRow(new Object[]{ 
                        rs.getInt("id"), 
                        rs.getString("nama_item"),
                        rs.getString("kode_lokasi"), 
                        rs.getString("stok_terkini") 
                    }); 
                } 

                // Atur model ke tabel UI
                TInventory.setModel(model); 

                // Beritahu UI bahwa data telah berubah agar visual langsung ter-render ulang
                model.fireTableDataChanged();

                // Sembunyikan kolom ID (Index 0) secara total agar aman dari resize manual user
                TInventory.getColumnModel().getColumn(0).setMinWidth(0); 
                TInventory.getColumnModel().getColumn(0).setMaxWidth(0); 
                TInventory.getColumnModel().getColumn(0).setPreferredWidth(0);

            } catch (SQLException e) { 
                JOptionPane.showMessageDialog(null, "Gagal memuat data: " + e.getMessage()); 
            } 
     }
    private void cariInventory() {

        String keyword = txtSearchInventory.getText();

        DefaultTableModel model =
            (DefaultTableModel) TInventory.getModel();

        model.setRowCount(0);

        try {

            Connection conn = DatabaseConfig.getConnection();

            String sql = """
               SELECT sh.id,  i.nama_item,l.kode_lokasi, sh.stok_terkini
                         FROM inventory sh 
                         INNER JOIN items i ON sh.item_id = i.id
                         INNER JOIN locations l ON sh.location_id = l.id
                         WHERE i.nama_item LIKE ?
                         OR l.kode_lokasi LIKE ?
                         OR sh.stok_terkini LIKE ?
                         ORDER BY sh.id DESC
            """;

            PreparedStatement ps =
                conn.prepareStatement(sql);

            ps.setString(1, "%" + keyword + "%");
            ps.setString(2, "%" + keyword + "%");
            ps.setString(3, "%" + keyword + "%");

            ResultSet rs = ps.executeQuery();

            while(rs.next()) {

                model.addRow(new Object[] {
                        rs.getInt("id"), 
                        rs.getString("nama_item"),
                        rs.getString("kode_lokasi"), 
                        rs.getString("stok_terkini") 
                });
            }

        } catch(Exception e) {

            JOptionPane.showMessageDialog(
                this,
                e.getMessage()
            );
        }
    }
    
     private void cariActivity() {

        String keyword = txtSearchActivity.getText();

        DefaultTableModel model =
            (DefaultTableModel) TActivity.getModel();

        model.setRowCount(0);

        try {

            Connection conn = DatabaseConfig.getConnection();

            String sql = """
                 SELECT sh.id, sh.waktu_transaksi, sh.jenis_transaksi, i.nama_item,l.kode_lokasi, sh.stock_sebelum, sh.stock_sesudah 
                                  FROM stock_history sh 
                                  INNER JOIN items i ON sh.item_id = i.id
                                  INNER JOIN locations l ON sh.location_id = l.id
                                   WHERE sh.waktu_transaksi  LIKE ?
                                     OR sh.jenis_transaksi  LIKE ?
                                     OR i.nama_item  LIKE ?
                                     OR l.kode_lokasi   LIKE ?
                                     OR sh.stock_sebelum   LIKE ?
                                      OR sh.stock_sesudah   LIKE ?
                                  ORDER BY sh.id DESC
            """;

            PreparedStatement ps =
                conn.prepareStatement(sql);

            ps.setString(1, "%" + keyword + "%");
            ps.setString(2, "%" + keyword + "%");
            ps.setString(3, "%" + keyword + "%");
            ps.setString(4, "%" + keyword + "%");
            ps.setString(5, "%" + keyword + "%");
            ps.setString(6, "%" + keyword + "%");

            ResultSet rs = ps.executeQuery();

            while(rs.next()) {

                model.addRow(new Object[] {
                        rs.getInt("id"), 
                      rs.getString("waktu_transaksi"),
                     rs.getString("jenis_transaksi"), 
                     rs.getString("nama_item"), 
                     rs.getString("kode_lokasi"), 
                     rs.getString("stock_sebelum"), 
                     rs.getString("stock_sesudah") 
                });
            }

        } catch(Exception e) {

            JOptionPane.showMessageDialog(
                this,
                e.getMessage()
            );
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BReportActivity;
    private javax.swing.JButton BReportInventory;
    private javax.swing.JLabel LBarangKeluar;
    private javax.swing.JLabel LBarangMasuk;
    private javax.swing.JLabel LInventory;
    private javax.swing.JTable TActivity;
    private javax.swing.JTable TInventory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtSearchActivity;
    private javax.swing.JTextField txtSearchInventory;
    // End of variables declaration//GEN-END:variables
}
