/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.warehouse.system.view;

import com.mycompany.warehouse.system.DatabaseConfig;
import com.mycompany.warehouse.system.service.DashboardService;
import static com.mycompany.warehouse.system.view.DashboardManager.instance;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import java.io.InputStream;

/**
 *
 * @author ndesc
 */
public class DashboardManager extends javax.swing.JPanel {
public static DashboardManager instance;
//--------ACTIVITY------------
private int currentPageActivity = 1;
private final int dataPerPageActivity = 10;

private int totalDataActivity = 0;
private int totalPageActivity = 0;

//--------INVENTORY------------
private int currentPageInventory = 1;
private final int dataPerPageInventory = 10;

private int totalDataInventory = 0;
private int totalPageInventory = 0;
    /**
     * Creates new form DashboardManager
     */
    public DashboardManager() {
          initComponents();
         instance = this;
          loadDataCount();
          
        BNInventory.setOpaque(true);
        BNInventory.setContentAreaFilled(true);
        BPInventory.setOpaque(true);
        BPInventory.setContentAreaFilled(true);
        hitungTotalDataInventory();
        loadDataInventory();
       
        
         
         
        BNActivity.setOpaque(true);
        BNActivity.setContentAreaFilled(true);
        BPActivity.setOpaque(true);
        BPActivity.setContentAreaFilled(true);
        hitungTotalDataActivity();
        loadDataAktifitas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        LInventory = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        LBarangMasuk = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        LBarangKeluar = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSearchInventory = new javax.swing.JTextField();
        BReportInventory = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TInventory = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        LPInventory = new javax.swing.JLabel();
        BPInventory = new javax.swing.JButton();
        BNInventory = new javax.swing.JButton();
        BSearchInventory = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSearchActivity = new javax.swing.JTextField();
        BReportActivity = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TActivity = new javax.swing.JTable();
        LPActivity = new javax.swing.JLabel();
        BPActivity = new javax.swing.JButton();
        BNActivity = new javax.swing.JButton();
        BSearchActivity = new javax.swing.JButton();

        setBackground(new java.awt.Color(248, 250, 252));

        header.setBackground(new java.awt.Color(248, 250, 252));
        header.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 10, 20));
        header.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Urbanist ExtraBold", 0, 18)); // NOI18N
        jLabel1.setText("Selamat datang di Gudangin.aja");
        header.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jLabel7.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(142, 157, 166));
        jLabel7.setText("Kelola stok barang dan pantau aktivitas gudang dengan lebih mudah.");
        header.add(jLabel7, java.awt.BorderLayout.CENTER);

        jPanel6.setBackground(new java.awt.Color(248, 250, 252));
        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0, 15, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(197, 203, 209), 1, true), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)));

        jLabel4.setFont(new java.awt.Font("Urbanist Medium", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(119, 130, 153));
        jLabel4.setText("Inventory");

        LInventory.setFont(new java.awt.Font("Inter ExtraBold", 0, 24)); // NOI18N
        LInventory.setForeground(new java.awt.Color(0, 51, 204));
        LInventory.setText("2.000");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LInventory, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(5, 5, 5)
                .addComponent(LInventory)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(197, 203, 209), 1, true), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)));

        jLabel5.setFont(new java.awt.Font("Urbanist Medium", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(119, 130, 153));
        jLabel5.setText("Barang Masuk");

        LBarangMasuk.setFont(new java.awt.Font("Inter ExtraBold", 0, 24)); // NOI18N
        LBarangMasuk.setForeground(new java.awt.Color(0, 153, 102));
        LBarangMasuk.setText("2.000");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
            .addComponent(LBarangMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(5, 5, 5)
                .addComponent(LBarangMasuk)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(197, 203, 209), 1, true), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)));

        jLabel6.setFont(new java.awt.Font("Urbanist Medium", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(119, 130, 153));
        jLabel6.setText("Barang Keluar");

        LBarangKeluar.setFont(new java.awt.Font("Inter ExtraBold", 0, 24)); // NOI18N
        LBarangKeluar.setForeground(new java.awt.Color(204, 0, 0));
        LBarangKeluar.setText("2.000");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
            .addComponent(LBarangKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(5, 5, 5)
                .addComponent(LBarangKeluar)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel4);

        jPanel7.setBackground(new java.awt.Color(248, 250, 252));
        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        jPanel7.setLayout(new java.awt.GridLayout(1, 0, 15, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(197, 203, 209), 1, true), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)));

        jLabel10.setFont(new java.awt.Font("Urbanist", 1, 16)); // NOI18N
        jLabel10.setText("Inventory");

        jLabel8.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(142, 157, 166));
        jLabel8.setText("Daftar barang yang tersedia.");

        txtSearchInventory.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        txtSearchInventory.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(197, 203, 209), 1, true), javax.swing.BorderFactory.createEmptyBorder(3, 8, 3, 8)));
        txtSearchInventory.setMargin(new java.awt.Insets(4, 10, 4, 10));
        txtSearchInventory.addActionListener(this::txtSearchInventoryActionPerformed);

        BReportInventory.setBackground(new java.awt.Color(255, 51, 102));
        BReportInventory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BReportInventory.setForeground(new java.awt.Color(255, 255, 255));
        BReportInventory.setText("Report");
        BReportInventory.setBorderPainted(false);
        BReportInventory.addActionListener(this::BReportInventoryActionPerformed);

        TInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama Barang", "Lokasi", "Stok Terkini"
            }
        ));
        TInventory.setShowGrid(true);
        jScrollPane1.setViewportView(TInventory);

        jLabel2.setText("Cari data:");

        LPInventory.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        LPInventory.setForeground(new java.awt.Color(142, 157, 166));
        LPInventory.setText("5 dari 10 data ditampilkan");

        BPInventory.setText("Previous");
        BPInventory.setBorderPainted(false);
        BPInventory.setEnabled(false);
        BPInventory.addActionListener(this::BPInventoryActionPerformed);

        BNInventory.setBackground(new java.awt.Color(0, 153, 204));
        BNInventory.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        BNInventory.setForeground(new java.awt.Color(255, 255, 255));
        BNInventory.setText("Next");
        BNInventory.setBorderPainted(false);
        BNInventory.addActionListener(this::BNInventoryActionPerformed);

        BSearchInventory.setBackground(new java.awt.Color(0, 153, 204));
        BSearchInventory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BSearchInventory.setText("Cari");
        BSearchInventory.addActionListener(this::BSearchInventoryActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LPInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(BPInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BNInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSearchInventory)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(16, 16, 16)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BReportInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BSearchInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(BReportInventory)))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchInventory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(BSearchInventory))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BNInventory)
                        .addComponent(BPInventory))
                    .addComponent(LPInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel1);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(197, 203, 209), 1, true), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)));

        jLabel11.setFont(new java.awt.Font("Urbanist", 1, 16)); // NOI18N
        jLabel11.setText("Aktivitas");

        jLabel9.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(142, 157, 166));
        jLabel9.setText("Daftar aktivitas barang.");

        txtSearchActivity.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        txtSearchActivity.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(197, 203, 209), 1, true), javax.swing.BorderFactory.createEmptyBorder(3, 8, 3, 8)));
        txtSearchActivity.addActionListener(this::txtSearchActivityActionPerformed);

        BReportActivity.setBackground(new java.awt.Color(255, 51, 102));
        BReportActivity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BReportActivity.setForeground(new java.awt.Color(255, 255, 255));
        BReportActivity.setText("Report");
        BReportActivity.setBorderPainted(false);
        BReportActivity.addActionListener(this::BReportActivityActionPerformed);

        jLabel3.setText("Cari data:");

        TActivity.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Jam", "Aktifitas", "Stok Sebelum", "Stok Sesudah"
            }
        ));
        TActivity.setShowGrid(true);
        jScrollPane2.setViewportView(TActivity);

        LPActivity.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        LPActivity.setForeground(new java.awt.Color(142, 157, 166));
        LPActivity.setText("5 dari 10 data ditampilkan");

        BPActivity.setText("Previous");
        BPActivity.setBorderPainted(false);
        BPActivity.setEnabled(false);
        BPActivity.addActionListener(this::BPActivityActionPerformed);

        BNActivity.setBackground(new java.awt.Color(0, 153, 204));
        BNActivity.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        BNActivity.setForeground(new java.awt.Color(255, 255, 255));
        BNActivity.setText("Next");
        BNActivity.setBorderPainted(false);
        BNActivity.addActionListener(this::BNActivityActionPerformed);

        BSearchActivity.setBackground(new java.awt.Color(0, 153, 204));
        BSearchActivity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BSearchActivity.setText("Cari");
        BSearchActivity.addActionListener(this::BSearchActivityActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(BReportActivity))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearchActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BSearchActivity))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(LPActivity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(BPActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BNActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel9))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(BReportActivity)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearchActivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BSearchActivity)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LPActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BNActivity)
                    .addComponent(BPActivity)))
        );

        jPanel7.add(jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchInventoryActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_txtSearchInventoryActionPerformed

    private void BReportInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BReportInventoryActionPerformed
          try {

                InputStream reportStream =
                    getClass().getResourceAsStream(
                        "/report/ReportInventory.jasper"
                    );

                HashMap<String, Object> parameters =
                    new HashMap<>();

                JasperPrint print =
                    JasperFillManager.fillReport(
                        reportStream,
                        parameters,
                        DatabaseConfig.getConnection()
                    );

                JasperViewer.viewReport(print, false);

            } catch (Exception e) {

                e.printStackTrace();
            }
    }//GEN-LAST:event_BReportInventoryActionPerformed

    private void BReportActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BReportActivityActionPerformed
          try {

                InputStream reportStream =
                    getClass().getResourceAsStream(
                        "/report/ReportHistory.jasper"
                    );

                HashMap<String, Object> parameters =
                    new HashMap<>();

                JasperPrint print =
                    JasperFillManager.fillReport(
                        reportStream,
                        parameters,
                        DatabaseConfig.getConnection()
                    );

                JasperViewer.viewReport(print, false);

            } catch (Exception e) {

                e.printStackTrace();
            }
    }//GEN-LAST:event_BReportActivityActionPerformed

    private void txtSearchActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActivityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActivityActionPerformed

    private void BPInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPInventoryActionPerformed
        // TODO add your handling code here:
          if (currentPageInventory > 1) {
            currentPageInventory--;
            loadDataInventory();
        }
    }//GEN-LAST:event_BPInventoryActionPerformed

    private void BNInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNInventoryActionPerformed
        // TODO add your handling code here:
         if (currentPageInventory < totalPageInventory) {
                currentPageInventory++;
                loadDataInventory();
            }
    }//GEN-LAST:event_BNInventoryActionPerformed

    private void BPActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPActivityActionPerformed
        // TODO add your handling code here:
         if (currentPageActivity > 1) {
            currentPageActivity--;
            loadDataAktifitas();
        }
    }//GEN-LAST:event_BPActivityActionPerformed

    private void BNActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNActivityActionPerformed
        // TODO add your handling code here:
         if (currentPageActivity < totalPageActivity) {
                currentPageActivity++;
                loadDataAktifitas();
            }
    }//GEN-LAST:event_BNActivityActionPerformed

    private void BSearchInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSearchInventoryActionPerformed
        // TODO add your handling code here:
        
             cariInventory();
    }//GEN-LAST:event_BSearchInventoryActionPerformed

    private void BSearchActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSearchActivityActionPerformed
        // TODO add your handling code here:
         cariActivity();
    }//GEN-LAST:event_BSearchActivityActionPerformed
   public final void loadDataCount(){
       LInventory.setText(String.valueOf(DashboardService.getTotalItemsInventory()));
        LBarangMasuk.setText(String.valueOf(DashboardService.getTotalItemsMasuk()));
        LBarangKeluar.setText(String.valueOf(DashboardService.getTotalItemsKeluar()));
    }
   
    public final void loadDataAktifitas() { 
        DefaultTableModel model = new DefaultTableModel() {

        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    model.addColumn("ID");
    model.addColumn("Jam");
    model.addColumn("Aktifitas");
    model.addColumn("Barang");
    model.addColumn("Lokasi");
    model.addColumn("Stok Sebelum");
    model.addColumn("Stok Sesudah");

    int offset = (currentPageActivity - 1) * dataPerPageActivity;

    String sql = """
        SELECT sh.id,
               sh.waktu_transaksi,
               sh.jenis_transaksi,
               i.nama_item,
               l.kode_lokasi,
               sh.stock_sebelum,
               sh.stock_sesudah
        FROM stock_history sh
        INNER JOIN items i ON sh.item_id = i.id
        INNER JOIN locations l ON sh.location_id = l.id
        ORDER BY sh.id DESC
        LIMIT ? OFFSET ?
        """;

    try (
        Connection conn = DatabaseConfig.getConnection();
        PreparedStatement ps = conn.prepareStatement(sql)
    ) {

        ps.setInt(1, dataPerPageActivity);
        ps.setInt(2, offset);

        ResultSet rs = ps.executeQuery();

        while (rs.next()) {

            model.addRow(new Object[]{
                rs.getInt("id"),
                rs.getString("waktu_transaksi"),
                rs.getString("jenis_transaksi"),
                rs.getString("nama_item"),
                rs.getString("kode_lokasi"),
                rs.getString("stock_sebelum"),
                rs.getString("stock_sesudah")
            });
        }

        TActivity.setModel(model);

        

        // Hide ID
        TActivity.getColumnModel().getColumn(0).setMinWidth(0);
        TActivity.getColumnModel().getColumn(0).setMaxWidth(0);
        TActivity.getColumnModel().getColumn(0).setPreferredWidth(0);

        // ===== UPDATE PAGINATION =====
        LPActivity.setText(
            "Page " + currentPageActivity + " / " + totalPageActivity
        );

        updatePaginationButtonActivity();

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
            null,
            "Gagal memuat data: " + e.getMessage()
        );
    }
     }
     private void updatePaginationButtonActivity() {
        // PREVIOUS
           BPActivity.setEnabled(currentPageActivity > 1);
           // NEXT
           BNActivity.setEnabled(currentPageActivity < totalPageActivity);
           // STYLE PREVIOUS
           if (BPActivity.isEnabled()) {
               BPActivity.setBackground(
                   new java.awt.Color(0,153,204)
               );
               BPActivity.setForeground(java.awt.Color.WHITE);

           } else {

               BPActivity.setBackground(
                   new java.awt.Color(220, 220, 220)
               );

               BPActivity.setForeground(
                   new java.awt.Color(120,120,120)
               );
           }

           // STYLE NEXT
           if (BNActivity.isEnabled()) {

               BNActivity.setBackground(
                   new java.awt.Color(0,153,204)
               );

               BNActivity.setForeground(java.awt.Color.WHITE);

           } else {

               BNActivity.setBackground(
                   new java.awt.Color(220,220,220)
               );

               BNActivity.setForeground(
                   new java.awt.Color(120,120,120)
               );
           }
       }
    private void cariActivity() {

        String keyword = txtSearchActivity.getText();

        DefaultTableModel model =
            (DefaultTableModel) TActivity.getModel();

        model.setRowCount(0);

        try {

            Connection conn = DatabaseConfig.getConnection();

            String sql = """
                 SELECT sh.id, sh.waktu_transaksi, sh.jenis_transaksi, i.nama_item,l.kode_lokasi, sh.stock_sebelum, sh.stock_sesudah 
                                  FROM stock_history sh 
                                  INNER JOIN items i ON sh.item_id = i.id
                                  INNER JOIN locations l ON sh.location_id = l.id
                                   WHERE sh.waktu_transaksi  LIKE ?
                                     OR sh.jenis_transaksi  LIKE ?
                                     OR i.nama_item  LIKE ?
                                     OR l.kode_lokasi   LIKE ?
                                     OR sh.stock_sebelum   LIKE ?
                                      OR sh.stock_sesudah   LIKE ?
                                  ORDER BY sh.id DESC
            """;

            PreparedStatement ps =
                conn.prepareStatement(sql);

            ps.setString(1, "%" + keyword + "%");
            ps.setString(2, "%" + keyword + "%");
            ps.setString(3, "%" + keyword + "%");
            ps.setString(4, "%" + keyword + "%");
            ps.setString(5, "%" + keyword + "%");
            ps.setString(6, "%" + keyword + "%");

            ResultSet rs = ps.executeQuery();

            while(rs.next()) {

                model.addRow(new Object[] {
                        rs.getInt("id"), 
                      rs.getString("waktu_transaksi"),
                     rs.getString("jenis_transaksi"), 
                     rs.getString("nama_item"), 
                     rs.getString("kode_lokasi"), 
                     rs.getString("stock_sebelum"), 
                     rs.getString("stock_sesudah") 
                });
            }

        } catch(Exception e) {

            JOptionPane.showMessageDialog(
                this,
                e.getMessage()
            );
        }
    }
     private void hitungTotalDataActivity() {

    String sql = "SELECT COUNT(*) AS total FROM stock_history";

    try (
        Connection conn = DatabaseConfig.getConnection();
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery()
    ) {

        if (rs.next()) {

            totalDataActivity = rs.getInt("total");

            totalPageActivity = (int) Math.ceil(
                (double) totalDataActivity / dataPerPageActivity
            );
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
            this,
            e.getMessage()
        );
    }
}
    
     
      public final void loadDataInventory() { 
                DefaultTableModel model = new DefaultTableModel() {
                    // Best practice: Membuat sel tabel tidak bisa diedit secara manual oleh user
                    @Override
                    public boolean isCellEditable(int row, int column) {
                        return false;
                    }
                };

        // Tambahkan kolom ID di index 0 
        model.addColumn("ID"); 
        model.addColumn("Nama Barang"); 
        model.addColumn("Lokasi"); 
        model.addColumn("Stok Terkini"); 
  
    int offset = (currentPageInventory - 1) * dataPerPageInventory;
        String sql = """
            SELECT sh.id,  i.nama_item,l.kode_lokasi, sh.stok_terkini
                        FROM inventory sh 
                        INNER JOIN items i ON sh.item_id = i.id
                        INNER JOIN locations l ON sh.location_id = l.id
                        ORDER BY sh.id DESC
            """;

            // Menggunakan try-with-resources untuk menutup conn, stmt, dan rs secara otomatis dan aman
            try (Connection conn = DatabaseConfig.getConnection();
                 PreparedStatement ps = conn.prepareStatement(sql);
                 ResultSet rs = ps.executeQuery()) { 

                while (rs.next()) { 
                    model.addRow(new Object[]{ 
                        rs.getInt("id"), 
                        rs.getString("nama_item"),
                        rs.getString("kode_lokasi"), 
                        rs.getString("stok_terkini") 
                    }); 
                } 

                // Atur model ke tabel UI
                TInventory.setModel(model); 

                // Beritahu UI bahwa data telah berubah agar visual langsung ter-render ulang
                model.fireTableDataChanged();

                // Sembunyikan kolom ID (Index 0) secara total agar aman dari resize manual user
                TInventory.getColumnModel().getColumn(0).setMinWidth(0); 
                TInventory.getColumnModel().getColumn(0).setMaxWidth(0); 
                TInventory.getColumnModel().getColumn(0).setPreferredWidth(0);

                
                // ===== UPDATE PAGINATION =====
                LPInventory.setText(
                    "Page " + currentPageActivity + " / " + totalPageActivity
                );
                updatePaginationButtonInventory();
            } catch (SQLException e) { 
                JOptionPane.showMessageDialog(null, "Gagal memuat data: " + e.getMessage()); 
            } 
     }
    private void updatePaginationButtonInventory() {
        // PREVIOUS
           BPInventory.setEnabled(currentPageInventory > 1);

           // NEXT
           BNInventory.setEnabled(currentPageActivity < totalPageInventory);

           // STYLE PREVIOUS
           if (BPInventory.isEnabled()) {

               BPInventory.setBackground(
                   new java.awt.Color(0,153,204)
               );

               BPInventory.setForeground(java.awt.Color.WHITE);

           } else {

               BPInventory.setBackground(
                   new java.awt.Color(220, 220, 220)
               );

               BPInventory.setForeground(
                   new java.awt.Color(120,120,120)
               );
           }

           // STYLE NEXT
           if (BNInventory.isEnabled()) {

               BNInventory.setBackground(
                   new java.awt.Color(0,153,204)
               );

               BNInventory.setForeground(java.awt.Color.WHITE);

           } else {

               BNInventory.setBackground(
                   new java.awt.Color(220,220,220)
               );

               BNInventory.setForeground(
                   new java.awt.Color(120,120,120)
               );
           }
       }
    private void cariInventory() {

        String keyword = txtSearchInventory.getText();

        DefaultTableModel model =
            (DefaultTableModel) TInventory.getModel();

        model.setRowCount(0);

        try {

            Connection conn = DatabaseConfig.getConnection();

            String sql = """
               SELECT sh.id,  i.nama_item,l.kode_lokasi, sh.stok_terkini
                         FROM inventory sh 
                         INNER JOIN items i ON sh.item_id = i.id
                         INNER JOIN locations l ON sh.location_id = l.id
                         WHERE i.nama_item LIKE ?
                         OR l.kode_lokasi LIKE ?
                         OR sh.stok_terkini LIKE ?
                         ORDER BY sh.id DESC
            """;

            PreparedStatement ps =
                conn.prepareStatement(sql);

            ps.setString(1, "%" + keyword + "%");
            ps.setString(2, "%" + keyword + "%");
            ps.setString(3, "%" + keyword + "%");

            ResultSet rs = ps.executeQuery();

            while(rs.next()) {

                model.addRow(new Object[] {
                        rs.getInt("id"), 
                        rs.getString("nama_item"),
                        rs.getString("kode_lokasi"), 
                        rs.getString("stok_terkini") 
                });
            }

        } catch(Exception e) {

            JOptionPane.showMessageDialog(
                this,
                e.getMessage()
            );
        }
    }
    private void hitungTotalDataInventory() {

    String sql = "SELECT COUNT(*) AS total FROM inventory";

    try (
        Connection conn = DatabaseConfig.getConnection();
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery()
    ) {

        if (rs.next()) {

            totalDataInventory = rs.getInt("total");

            totalPageInventory = (int) Math.ceil(
                (double) totalDataInventory / dataPerPageInventory
            );
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
            this,
            e.getMessage()
        );
    }
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BNActivity;
    private javax.swing.JButton BNInventory;
    private javax.swing.JButton BPActivity;
    private javax.swing.JButton BPInventory;
    private javax.swing.JButton BReportActivity;
    private javax.swing.JButton BReportInventory;
    private javax.swing.JButton BSearchActivity;
    private javax.swing.JButton BSearchInventory;
    private javax.swing.JLabel LBarangKeluar;
    private javax.swing.JLabel LBarangMasuk;
    private javax.swing.JLabel LInventory;
    private javax.swing.JLabel LPActivity;
    private javax.swing.JLabel LPInventory;
    private javax.swing.JTable TActivity;
    private javax.swing.JTable TInventory;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtSearchActivity;
    private javax.swing.JTextField txtSearchInventory;
    // End of variables declaration//GEN-END:variables
}
