/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.warehouse.system.view;

import com.mycompany.warehouse.system.model.User;
import com.mycompany.warehouse.system.service.UserService;
import com.mycompany.warehouse.system.service.Session;

/**
 *
 * @author ndesc
 */

public class FormLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormLogin.class.getName());

    /**
     * Creates new form form_logins
     */
    public FormLogin() {
        initComponents();
      java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();

    int width = screenSize.width / 2;
    int height = screenSize.height / 2;

    this.setSize(width, height);
    this.setLocationRelativeTo(null); // center
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tpassword = new javax.swing.JPasswordField();
        tusername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        blogin1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        label2 = new java.awt.Label();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(238, 245, 249));

        tpassword.setToolTipText("");
        tpassword.setCaretColor(new java.awt.Color(246, 246, 246));
        tpassword.setDisabledTextColor(new java.awt.Color(139, 142, 153));
        tpassword.addActionListener(this::tpasswordActionPerformed);

        tusername.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tusername.setCaretColor(new java.awt.Color(244, 244, 245));
        tusername.setDisabledTextColor(new java.awt.Color(138, 141, 151));
        tusername.setName(""); // NOI18N
        tusername.addActionListener(this::tusernameActionPerformed);

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        blogin1.setBackground(new java.awt.Color(37, 90, 182));
        blogin1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        blogin1.setForeground(new java.awt.Color(255, 255, 255));
        blogin1.setText("Login");
        blogin1.setBorderPainted(false);
        blogin1.addActionListener(this::blogin1ActionPerformed);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Gudangin.aja");
        jLabel1.setDoubleBuffered(true);

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        label2.setText("2026 © copyright - Kelompok 2");

        jLabel7.setText("Selamat datang di aplikasi Gudangin.aja.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(blogin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tpassword)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tusername)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(tusername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(tpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(blogin1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 390, 480);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login4.jpg"))); // NOI18N
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setPreferredSize(new java.awt.Dimension(600, 1024));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(390, 0, 410, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void blogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blogin1ActionPerformed
            // 1. Ambil input dari JTextField/JPasswordField
String username = tusername.getText();
String password = new String(tpassword.getPassword());

// 2. Cek apakah input kosong
if (username.isEmpty() || password.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(
        this,
        "Username dan Password tidak boleh kosong!"
    );
    return;
}

// 3. Disable tombol & tampilkan loading
blogin1.setEnabled(false);
blogin1.setText("Loading...");
this.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.WAIT_CURSOR));

// 4. Jalankan autentikasi + load dashboard di background thread
new javax.swing.SwingWorker<ContentFrame, Void>() {
    private User userResult;

    @Override
    protected ContentFrame doInBackground() {
        // Authenticate (koneksi DB ke TiDB Cloud)
        userResult = UserService.authenticate(username, password);
        if (userResult == null) return null;

        // Set session
        Session.setUser(userResult);

        // Buat ContentFrame (load semua panel + data dari DB)
        return new ContentFrame();
    }

    @Override
    protected void done() {
        try {
            ContentFrame dash = get();
            if (dash != null) {
                // Login berhasil — buka dashboard
                dash.setLocationRelativeTo(null);
                dash.setVisible(true);
                FormLogin.this.dispose();
            } else {
                // Login gagal
                javax.swing.JOptionPane.showMessageDialog(FormLogin.this,
                        "Username atau Password Salah / Tidak Ditemukan",
                        "Login Gagal",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                tpassword.setText("");
                tusername.requestFocus();
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(FormLogin.this,
                    "Terjadi kesalahan: " + ex.getMessage());
        } finally {
            blogin1.setEnabled(true);
            blogin1.setText("Login");
            FormLogin.this.setCursor(java.awt.Cursor.getDefaultCursor());
        }
    }
}.execute();
    }//GEN-LAST:event_blogin1ActionPerformed

    private void tusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tusernameActionPerformed

    private void tpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blogin1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label2;
    private javax.swing.JPasswordField tpassword;
    private javax.swing.JTextField tusername;
    // End of variables declaration//GEN-END:variables
}
