/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.warehouse.system.view;

import com.mycompany.warehouse.system.DatabaseConfig;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ndesc
 */
public class RakPanel extends javax.swing.JPanel {

    private int selectedId = -1;
    private TableRowSorter<DefaultTableModel> rowSorter;
    private final java.util.List<Integer> locationIds = new java.util.ArrayList<>();

    /** Creates new form LocationPanel */
    public RakPanel() {
        initComponents();
        setupSearch();
        setupTable();
        loadData();
    }

    /**
     * Bungkus panel ini ke dalam JScrollPane (untuk scroll vertikal/horizontal).
     * Dipanggil oleh ContentFrame saat menambah panel ke CardLayout.
     * @return JScrollPane yang membungkus panel ini.
     */
    public javax.swing.JScrollPane asScrollable() {
        javax.swing.JScrollPane sp = new javax.swing.JScrollPane(this);
        sp.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        sp.getVerticalScrollBar().setUnitIncrement(16);
        sp.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        sp.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);
        return sp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        jPanelForm = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        labelDesc = new java.awt.Label();
        jLabelZona = new javax.swing.JLabel();
        txtZona = new javax.swing.JTextField();
        jLabelRak = new javax.swing.JLabel();
        txtRak = new javax.swing.JTextField();
        jLabelLevelRak = new javax.swing.JLabel();
        txtLevelRak = new javax.swing.JTextField();
        jLabelKapasitas = new javax.swing.JLabel();
        txtKapasitas = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelTable = new javax.swing.JLabel();
        labelTableDesc = new java.awt.Label();
        jPanelTable = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        labelInfo = new java.awt.Label();

        setBackground(new java.awt.Color(244, 245, 246));

        jLabel1.setFont(new java.awt.Font("Urbanist", 1, 16)); // NOI18N
        jLabel1.setText("Manajemen Rak");

        label1.setBackground(new java.awt.Color(242, 242, 242));
        label1.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        label1.setForeground(new java.awt.Color(142, 157, 166));
        label1.setText("Kelola semua data rak gudang.");

        jPanelForm.setBackground(new java.awt.Color(255, 255, 255));
        jPanelForm.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(197, 203, 209), 1, true), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)));

        jLabelTitle.setFont(new java.awt.Font("Urbanist", 1, 14)); // NOI18N
        jLabelTitle.setText("Informasi Rak");

        labelDesc.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        labelDesc.setForeground(new java.awt.Color(142, 157, 166));
        labelDesc.setText("Silahkan isi form berikut untuk menambahkan data rak, data otomatis masuk ke tabel rak.");

        jLabelZona.setText("Zona");

        jLabelRak.setText("Rak");

        jLabelLevelRak.setText("Level Rak");

        jLabelKapasitas.setText("Kapasitas Maksimum");

        btnSimpan.setBackground(new java.awt.Color(39, 174, 96));
        btnSimpan.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan Data");
        btnSimpan.setBorderPainted(false);
        btnSimpan.setFocusPainted(false);
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        btnReset.setBackground(new java.awt.Color(51, 0, 102));
        btnReset.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.setBorderPainted(false);
        btnReset.setFocusPainted(false);
        btnReset.addActionListener(this::btnResetActionPerformed);

        btnHapus.setBackground(new java.awt.Color(192, 57, 43));
        btnHapus.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus Data");
        btnHapus.setBorderPainted(false);
        btnHapus.setFocusPainted(false);
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        javax.swing.GroupLayout jPanelFormLayout = new javax.swing.GroupLayout(jPanelForm);
        jPanelForm.setLayout(jPanelFormLayout);
        jPanelFormLayout.setHorizontalGroup(
            jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelZona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtZona)
            .addComponent(jLabelRak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtRak)
            .addComponent(jLabelLevelRak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtLevelRak)
            .addComponent(jLabelKapasitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtKapasitas)
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addComponent(btnSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHapus)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelFormLayout.setVerticalGroup(
            jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addComponent(jLabelTitle)
                .addGap(2, 2, 2)
                .addComponent(labelDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabelZona)
                .addGap(4, 4, 4)
                .addComponent(txtZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelRak)
                .addGap(4, 4, 4)
                .addComponent(txtRak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelLevelRak)
                .addGap(4, 4, 4)
                .addComponent(txtLevelRak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelKapasitas)
                .addGap(4, 4, 4)
                .addComponent(txtKapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnReset)
                    .addComponent(btnHapus)))
        );

        jLabelTable.setFont(new java.awt.Font("Urbanist", 1, 16)); // NOI18N
        jLabelTable.setText("Table Data Rak");

        labelTableDesc.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        labelTableDesc.setForeground(new java.awt.Color(142, 157, 166));
        labelTableDesc.setText("List data rak yang tersedia.");

        jPanelTable.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTable.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(197, 203, 209), 1, true), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)));

        txtSearch.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        txtSearch.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtSearch.setText("Cari data..");
        txtSearch.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(225, 228, 231), 1, true), javax.swing.BorderFactory.createEmptyBorder(6, 10, 6, 10)));

        jTable1.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Lokasi", "Zona", "Rak", "Level Rak", "Kapasitas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(225, 228, 231));
        jTable1.setRowHeight(28);
        jTable1.setSelectionBackground(new java.awt.Color(184, 207, 229));
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        labelInfo.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        labelInfo.setForeground(new java.awt.Color(142, 157, 166));
        labelInfo.setText("Total data rak.");

        javax.swing.GroupLayout jPanelTableLayout = new javax.swing.GroupLayout(jPanelTable);
        jPanelTable.setLayout(jPanelTableLayout);
        jPanelTableLayout.setHorizontalGroup(
            jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSearch)
            .addComponent(jScrollPane1)
            .addComponent(labelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelTableLayout.setVerticalGroup(
            jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTableLayout.createSequentialGroup()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jLabelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTableDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jPanelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabelTable)
                .addGap(0, 0, 0)
                .addComponent(labelTableDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanelTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        simpanData();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        clearForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        hapusData();
    }//GEN-LAST:event_btnHapusActionPerformed

    // ============================================================
    // BUSINESS LOGIC: CRUD Lokasi
    // ============================================================

    public final void loadData() {
        DefaultTableModel model = new DefaultTableModel(
                new String[]{"Kode Lokasi", "Zona", "Rak", "Level Rak", "Kapasitas"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) { return false; }
        };

        locationIds.clear();
        try (Connection conn = DatabaseConfig.getConnection()) {
            String sql = "SELECT id, kode_lokasi, zona, rak, level_rak, kapasitas_maksimum "
                    + "FROM locations WHERE status_aktif = 1 ORDER BY id ASC";
            ResultSet rs = conn.createStatement().executeQuery(sql);
            while (rs.next()) {
                locationIds.add(rs.getInt("id"));
                model.addRow(new Object[]{
                    rs.getString("kode_lokasi"),
                    rs.getString("zona"),
                    rs.getString("rak"),
                    rs.getString("level_rak"),
                    rs.getInt("kapasitas_maksimum")
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }

        jTable1.setModel(model);
        rowSorter = new TableRowSorter<>(model);
        jTable1.setRowSorter(rowSorter);

        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);

        // Force warna teks hitam dengan custom renderer
        javax.swing.table.DefaultTableCellRenderer cellRenderer = new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                setForeground(java.awt.Color.BLACK);
                setBackground(isSelected ? new java.awt.Color(184, 207, 229) : java.awt.Color.WHITE);
                setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 8, 4, 8));
                return this;
            }
        };
        jTable1.setDefaultRenderer(Object.class, cellRenderer);

        // Set tinggi scrollPane = header + (rowCount × rowHeight) + 2px buffer
        int headerHeight = jTable1.getTableHeader().getPreferredSize().height;
        int contentHeight = model.getRowCount() * jTable1.getRowHeight();
        int minHeight = headerHeight + jTable1.getRowHeight();
        int finalHeight = Math.max(minHeight, headerHeight + contentHeight + 2);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(0, finalHeight));
        jPanelTable.revalidate();
        jPanelTable.repaint();

        labelInfo.setText("Total " + model.getRowCount() + " data lokasi.");
    }

    private String generateKodeLokasi(String zona, String rak, String levelRak) {
        // Format: LOC-ZONA-RAK-LEVEL
        String z = zona.trim().toUpperCase().replaceAll("\\s+", "");
        String r = rak.trim().toUpperCase().replaceAll("\\s+", "");
        String l = levelRak.trim().toUpperCase().replaceAll("\\s+", "");
        return "LOC-" + z + "-" + r + "-" + l;
    }

    private void simpanData() {
        String zona = txtZona.getText().trim();
        String rak = txtRak.getText().trim();
        String levelRak = txtLevelRak.getText().trim();
        String kapasitas = txtKapasitas.getText().trim();

        if (zona.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Zona tidak boleh kosong!");
            txtZona.requestFocus();
            return;
        }

        try (Connection conn = DatabaseConfig.getConnection()) {
            if (selectedId == -1) {
                String kodeLokasi = generateKodeLokasi(zona, rak, levelRak);
                String sql = "INSERT INTO locations (kode_lokasi, zona, rak, level_rak, kapasitas_maksimum, status_aktif, created_at, updated_at) "
                        + "VALUES (?, ?, ?, ?, ?, 1, NOW(), NOW())";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, kodeLokasi);
                ps.setString(2, zona);
                ps.setString(3, rak);
                ps.setString(4, levelRak);
                ps.setInt(5, kapasitas.isEmpty() ? 0 : Integer.parseInt(kapasitas));
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data rak berhasil disimpan!");
            } else {
                String sql = "UPDATE locations SET zona=?, rak=?, level_rak=?, kapasitas_maksimum=?, updated_at=NOW() WHERE id=?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, zona);
                ps.setString(2, rak);
                ps.setString(3, levelRak);
                ps.setInt(4, kapasitas.isEmpty() ? 0 : Integer.parseInt(kapasitas));
                ps.setInt(5, selectedId);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data rak berhasil diupdate!");
            }
            clearForm();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Kapasitas harus berupa angka!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
        }
    }

    private void hapusData() {
        if (selectedId == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data rak yang ingin dihapus dari tabel!");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin menghapus rak ini?",
                "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try (Connection conn = DatabaseConfig.getConnection()) {
                String sql = "UPDATE locations SET status_aktif = 0, updated_at = NOW() WHERE id = ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setInt(1, selectedId);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data rak berhasil dihapus!");
                clearForm();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage());
            }
        }
    }

    private void clearForm() {
        txtZona.setText("");
        txtRak.setText("");
        txtLevelRak.setText("");
        txtKapasitas.setText("");
        selectedId = -1;
        btnSimpan.setText("Simpan Data");
        txtZona.requestFocus();
        loadData();
    }

    // ============================================================
    // SETUP: Search & Table interaction
    // ============================================================

    private void setupSearch() {
        final String placeholder = "Cari data..";
        txtSearch.setText(placeholder);
        txtSearch.setForeground(new java.awt.Color(150, 150, 150));

        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtSearch.getText().equals(placeholder)) {
                    txtSearch.setText("");
                    txtSearch.setForeground(java.awt.Color.BLACK);
                }
            }
            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtSearch.getText().isEmpty()) {
                    txtSearch.setText(placeholder);
                    txtSearch.setForeground(new java.awt.Color(150, 150, 150));
                }
            }
        });

        txtSearch.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override public void insertUpdate(javax.swing.event.DocumentEvent e) { filterTable(); }
            @Override public void removeUpdate(javax.swing.event.DocumentEvent e) { filterTable(); }
            @Override public void changedUpdate(javax.swing.event.DocumentEvent e) { filterTable(); }
        });
    }

    private void filterTable() {
        String keyword = txtSearch.getText();
        if (keyword.equals("Cari data..")) keyword = "";
        if (rowSorter != null) {
            if (keyword.trim().isEmpty()) {
                rowSorter.setRowFilter(null);
            } else {
                rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + java.util.regex.Pattern.quote(keyword)));
            }
        }
    }

    private void setupTable() {
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int viewRow = jTable1.getSelectedRow();
                if (viewRow < 0) return;
                int row = jTable1.convertRowIndexToModel(viewRow);
                if (row >= 0 && row < locationIds.size()) {
                    selectedId = locationIds.get(row);
                    javax.swing.table.TableModel m = jTable1.getModel();
                    // columns: 0=Kode Lokasi, 1=Zona, 2=Rak, 3=Level Rak, 4=Kapasitas
                    txtZona.setText(String.valueOf(m.getValueAt(row, 1)));
                    txtRak.setText(String.valueOf(m.getValueAt(row, 2)));
                    txtLevelRak.setText(String.valueOf(m.getValueAt(row, 3)));
                    txtKapasitas.setText(String.valueOf(m.getValueAt(row, 4)));
                    btnSimpan.setText("Update Data");
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelKapasitas;
    private javax.swing.JLabel jLabelLevelRak;
    private javax.swing.JLabel jLabelRak;
    private javax.swing.JLabel jLabelTable;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelZona;
    private javax.swing.JPanel jPanelForm;
    private javax.swing.JPanel jPanelTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private java.awt.Label label1;
    private java.awt.Label labelDesc;
    private java.awt.Label labelInfo;
    private java.awt.Label labelTableDesc;
    private javax.swing.JTextField txtKapasitas;
    private javax.swing.JTextField txtLevelRak;
    private javax.swing.JTextField txtRak;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtZona;
    // End of variables declaration//GEN-END:variables
}
